#include "hashMap.h"
#include "BallsNBinsExperiment.h"
#include "CuckooHashMap.h"
#include "HopscotchHashMap.h"

#include <iostream>
#include <string>
#include <vector>
#include <cstring>
#include <cmath>
#include <random>

/* ---------- Hash Functions ---------- */
size_t stringHash(const std::string& s) {
    size_t h = 0;
    for (char c : s)
        h = 31 * h + c;
    return h;
}

size_t intHash(const int& k) {
    return static_cast<size_t>(k);
}
size_t intHash1(int k) {
    return static_cast<size_t>(k);
}

size_t intHash2(int k) {
    static constexpr double A = 0.6180339887498948482;
    double frac = k * A - std::floor(k * A);
    return static_cast<size_t>(frac * 1e9);
}


int main() {
 /* ----- opgave hvor alle keys hasher til samme indeks med inthash ----*/
    size_t tbSize = 13;
    int keys[13];              // eller: int keys[tbSize]; hvis din compiler tillader VLA
    int idx = 3;

    std::cout << "autogenerated keys" << std::endl;
    for (size_t i = 0; i < tbSize; i++) {
        keys[i] = static_cast<int>(i * tbSize + idx);
        std::cout << "keys[" << i << "]: " << keys[i] << std::endl;
    }
    std::cout << std::endl;

    /*---------- Linear Probing ----------*/
    HashMap<int, int> hmLinear(
        tbSize,
        intHash,
        ProbingMode::LinearProbing,
        true,      // enable rehash
        0.7        // max load factor
    );

    for (int key : keys) {
        hmLinear.insert(key, 1);
    }

    std::cout << "Linear Probing Table:\n";
    hmLinear.debugPrint();

    /*---------- Quadratic Probing ----------*/
    HashMap<int, int> hmQuadratic(
        tbSize,
        intHash,
        ProbingMode::QuadraticProbing,
        true,
        0.7
    );

    for (int key : keys) {
        hmQuadratic.insert(key, 1);
    }

    std::cout << "Quadratic Probing Table:\n";
    hmQuadratic.debugPrint();

    return 0;
}
